[package]
name = "sqlite-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log= "*"
env_logger = "0.9.0"
serde = { version = "*", features = ["derive"] }
serde_json = "*"